image: node:15-alpine
stages:
  - docker

build-docker:
  image: docker:latest
  variables:
    DOCKER_DRIVER: overlay
    CRYPTOGRAPHY_DONT_BUILD_RUST: 1
  services:
  - docker:dind
  stage: docker
  environment: staging
  script:
    - echo "Build docker ðŸ³"
    - touch .env
    - echo "ENVIRONMENT=${ENVIRONMENT}" > .env
    - echo "POKEAPI_BASE_URL=${POKEAPI_BASE_URL}" >> .env
    - echo "POKEAPI_LIMIT=${POKEAPI_LIMIT}" >> .env
    - echo "FAVORITE_STORAGE=${FAVORITE_STORAGE}" >> .env
    - docker build . -t=expo-pokedex-app:gitlab-ci-b-${CI_PIPELINE_IID}